# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 17:00
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        ('viewflow', '0006_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_step', models.CharField(blank=True, max_length=255, null=True, verbose_name='Для какого шага создана Корректировка')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Данные о коррекции')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Корректировки актуальны?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('fixed_in_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections_fixed', to='reversion.Version', verbose_name='В какой версии корректировки исправленны')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Корректировка',
                'verbose_name_plural': 'Корректировка',
            },
        ),
        migrations.CreateModel(
            name='ProposalProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('inn', models.CharField(max_length=255, verbose_name='ИНН')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('account_number', models.CharField(max_length=255, verbose_name='Номер расчётного счёта')),
                ('j_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='J-код')),
                ('is_needs_bibserve_account', models.BooleanField(default=False, verbose_name='Is client needs to have a BibServe account?')),
                ('bibserve_login', models.CharField(blank=True, max_length=255, null=True, verbose_name='BibServe Login')),
                ('bibserve_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='BibServe Password')),
                ('acs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acs_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер по работе с клиентами')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Регистрируемый клиент')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
            bases=('viewflow.process',),
        ),
        migrations.AddField(
            model_name='correction',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProposalProcess', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='correction',
            name='reviewed_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections_reviewed', to='reversion.Version', verbose_name='К какой версии заявки относятся корректировки'),
        ),
        migrations.AddField(
            model_name='correction',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewflow.Task', verbose_name='На каком шаге создана Корректировка'),
        ),
    ]
