# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalprocess',
            name='d_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='D-код'),
        ),
    ]
