# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 07:56
from __future__ import unicode_literals

from django.db import migrations


def delete_all_corrections(apps, schema_editor):
    Correction = apps.get_model('main', 'Correction')
    Correction.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_all_corrections),
    ]
