# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        ('viewflow', '0006_i18n'),
        ('main', '0002_auto_20180111_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='proposal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ProposalProcess', verbose_name='Заявка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correction',
            name='reviewed_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reversion.Version', verbose_name='К какой версии заявки относятся корректировки'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='correction',
            unique_together=set([('proposal', 'task')]),
        ),
    ]
