# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0006_i18n'),
        ('main', '0002_proposalprocess_d_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibServeProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('login', models.CharField(blank=True, max_length=255, null=True, verbose_name='Login')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='Password')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProposalProcess', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'BibServe аккаунт',
                'verbose_name_plural': 'BibServe аккаунты',
            },
            bases=('viewflow.process',),
        ),
    ]
