# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bibserveprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibserveprocess',
            name='is_allowed_to_activate',
            field=models.BooleanField(default=False, verbose_name='Is allowed to activate'),
        ),
        migrations.AlterField(
            model_name='bibserveprocess',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.ProposalProcess', verbose_name='Заявка'),
        ),
    ]
