# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180208_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalprocess',
            name='mdm_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MDM ID'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='person_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
