# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180219_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalprocess',
            name='person_name',
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='person_email',
            field=models.CharField(default='', max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='person_first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='person_last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='mdm_id',
            field=models.CharField(default='', max_length=255, verbose_name='MDM ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='phone',
            field=models.CharField(default='', max_length=255, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
