# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0006_i18n'),
        ('main', '0006_auto_20180227_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperdocsprocess',
            name='process_ptr',
        ),
        migrations.RemoveField(
            model_name='paperdocsprocess',
            name='proposal',
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='person_email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.DeleteModel(
            name='PaperDocsProcess',
        ),
    ]
