# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180221_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalprocess',
            name='person_login',
            field=models.CharField(default='', max_length=255, verbose_name='Login пользователя'),
            preserve_default=False,
        ),
    ]
