# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180228_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalprocess',
            old_name='person_login',
            new_name='client_login',
        ),
        migrations.RemoveField(
            model_name='proposalprocess',
            name='person_email',
        ),
        migrations.RemoveField(
            model_name='proposalprocess',
            name='person_first_name',
        ),
        migrations.RemoveField(
            model_name='proposalprocess',
            name='person_last_name',
        ),
        migrations.RemoveField(
            model_name='proposalprocess',
            name='phone',
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Факт. Адрес'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='bank_details',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Информация о банке'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='bibserve_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BibServe email'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='bibserve_tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BibServe tel'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='bik',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank identifier code'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='block',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Факт. Корпус'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='buh_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бухгалтер e-mail'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='buh_fax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бухгалтер fax'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='buh_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бухгалтер ФИО'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='buh_tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бухгалтер телефон'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='building',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Факт. Строение'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название клиента'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт e-mail'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='contact_fax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт fax'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт ФИО'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='contact_tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакт телефон'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='contract_date',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='contract_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер договора'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='corr_account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер корр. счёта'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, Адрес'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_block',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, Корпус'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_building',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, Строение'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, Город'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_client_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, Название клиента'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, Контактное лицо'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, Страна'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, e-mail'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_fax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, fax'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, Регион'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, Улица'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, телефон'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_zip_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Доставка, Индекс'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='dir_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Директор e-mail'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='dir_fax',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Директор fax'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='dir_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Директор ФИО'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='dir_tel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Директор телефон'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='jur_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. Адрес'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='jur_block',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. Корпус'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='jur_building',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. Строение'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='jur_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. Город'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='jur_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. Страна'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='jur_form',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус компании'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='jur_region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. Регион'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='jur_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. Улица'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='jur_zip_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Юр. Индекс'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='kpp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='ogrn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='okpo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ОКПО'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='operation_type',
            field=models.IntegerField(choices=[(0, 'Открытие'), (1, 'Изменение'), (2, 'Закрытие')], default=0, verbose_name='Формат ОИЗ'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Факт. Регион'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Факт. Улица'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_2r',
            field=models.IntegerField(default=0, verbose_name='2R'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_ag',
            field=models.IntegerField(default=0, verbose_name='GC'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_break_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Перерыв c'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_break_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Перерыв до'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарии к работе склада'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_consignee_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код грузополучателя'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_gc',
            field=models.IntegerField(default=0, verbose_name='GC'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_pl',
            field=models.IntegerField(default=0, verbose_name='PL'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_station_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код станции'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_tc',
            field=models.IntegerField(default=0, verbose_name='TC'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_working_days',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дни работы склада'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_working_hours_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Часы работы склада с'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='warehouse_working_hours_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Часы работы склада до'),
        ),
        migrations.AddField(
            model_name='proposalprocess',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Факт. Индекс'),
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер расчётного счёта'),
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка'),
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Факт. Город'),
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Факт. Страна'),
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='inn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН'),
        ),
    ]
