# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180228_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalprocess',
            name='client_email',
            field=models.CharField(default='', max_length=255, verbose_name='Email пользователя'),
            preserve_default=False,
        ),
    ]
