# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_proposalprocess_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalprocess',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании'),
        ),
    ]
