# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180303_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalprocess',
            name='delivery_address_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Доставка, Комментарии к адресу'),
        ),
    ]
