# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_proposalprocess_delivery_address_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalprocess',
            name='warehouse_2r',
            field=models.IntegerField(blank=True, null=True, verbose_name='2R'),
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='warehouse_ag',
            field=models.IntegerField(blank=True, null=True, verbose_name='GC'),
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='warehouse_gc',
            field=models.IntegerField(blank=True, null=True, verbose_name='GC'),
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='warehouse_pl',
            field=models.IntegerField(blank=True, null=True, verbose_name='PL'),
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='warehouse_tc',
            field=models.IntegerField(blank=True, null=True, verbose_name='TC'),
        ),
    ]
