# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180304_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='warehouse_working_hours_from',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Часы работы с'),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='warehouse_working_hours_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Часы работы до'),
        ),
        migrations.AlterField(
            model_name='proposalprocess',
            name='is_needs_bibserve_account',
            field=models.BooleanField(default=False, verbose_name='Нужна ли регистрация в BibServe?'),
        ),
    ]
